services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - hrd-register-api

  storage:
    image: minio/minio:latest
    command: minio server /var/lib/minio/data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage_data:/var/lib/minio/data
    networks:
      - hrd-register-api

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
      - storage
    ports:
      - "8083:8080"
    networks:
      - hrd-register-api
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      JWT_SECRET_KEY: ${JWT_SECRET_KEY}

      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}

      MINIO_URL: ${MINIO_URL}
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}

      WEBILL_URL: ${WEBILL_URL}
      WEBILL_CLIENT_ID: ${WEBILL_CLIENT_ID}
      WEBILL_CLIENT_SECRET: ${WEBILL_CLIENT_SECRET}
      WEBILL_ACCOUNT_NAME: ${WEBILL_ACCOUNT_NAME}
      WEBILL_ACCOUNT_NO: ${WEBILL_ACCOUNT_NO}

volumes:
  db_data:
  storage_data:

networks:
  hrd-register-api:
    external: true
