spring:
  application:
    name: hrd-register-api

  jackson:
    deserialization:
      ACCEPT_EMPTY_STRING_AS_NULL_OBJECT: true
      READ_UNKNOWN_ENUM_VALUES_AS_NULL: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 5KB
      max-file-size: 5MB
      max-request-size: 10MB

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration: 18000

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh

minio:
  url: ${MINIO_URL}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}

webill:
  URL: ${WEBILL_URL}
  client-id: ${WEBILL_CLIENT_ID}
  client-secret: ${WEBILL_CLIENT_SECRET}
  account-name: ${WEBILL_ACCOUNT_NAME}
  account-no: ${WEBILL_ACCOUNT_NO}
