INSERT INTO baciis (grade)
VALUES ('Grade A'),
       ('Grade B'),
       ('Grade C'),
       ('Grade D'),
       ('Grade E'),
       ('Grade Auto'),
       ('Other');

INSERT INTO addresses (name)
VALUES ('Tuol Kouk'),
       ('Sen Sok'),
       ('Russey Keo'),
       ('Prek Pnov'),
       ('Prampir Makara'),
       ('Pou Senchey'),
       ('Mean Chey'),
       ('Kamboul'),
       ('Daun Penh'),
       ('Dangkao'),
       ('Chroy Changvar'),
       ('Chbar Ampov'),
       ('Chamkar Mon'),
       ('Boeng Keng Kang'),
       ('Prek Kompoeus'),
       ('Other');

INSERT INTO educations (level_of_education)
VALUES ('Year 2 Semester 2'),
       ('Year 3 Semester 1'),
       ('Year 3 Semester 2'),
       ('Year 4 Semester 1'),
       ('Year 4 Semester 2'),
       ('Graduated');

INSERT INTO provinces (name)
VALUES ('Phnom Penh'),
       ('Kampong Cham'),
       ('Siem Reap'),
       ('Banteay Meanchey'),
       ('Battambang'),
       ('Kampong Chhnang'),
       ('Kampong Speu'),
       ('Kampong Thom'),
       ('Kampot'),
       ('Kandal'),
       ('Koh Kong'),
       ('Kep'),
       ('Kratie'),
       ('Mondulkiri'),
       ('Oddar Meanchey'),
       ('Pailin'),
       ('Preah Sihanouk'),
       ('Preah Vihear'),
       ('Pursat'),
       ('Prey Veng'),
       ('Ratanakiri'),
       ('Stung Treng'),
       ('Svay Rieng'),
       ('Takeo'),
       ('Tboung Khmum');

INSERT INTO universities (abbreviation)
VALUES ('RUPP'),
       ('SETEC'),
       ('BBU'),
       ('PUC'),
       ('PPIU'),
       ('NU'),
       ('UBB'),
       ('AEU'),
       ('UME'),
       ('RAC'),
       ('CARDI'),
       ('ITC'),
       ('CSUK'),
       ('NIE'),
       ('NTTI'),
       ('PNCA'),
       ('RUA'),
       ('RUFA'),
       ('RULE'),
       ('SRU'),
       ('UHS'),
       ('IIC'),
       ('UC'),
       ('UP'),
       ('PPIT'),
       ('CamEd'),
       ('SPI'),
       ('BELTEI'),
       ('CMU'),
       ('AUPP'),
       ('CUS'),
       ('NUM'),
       ('PCU'),
       ('PARAGON'),
       ('NIB'),
       ('AIB'),
       ('WU'),
       ('CADT'),
       ('AU');

INSERT INTO generations (generation)
VALUES ('1st Generation'),
       ('2nd Generation'),
       ('3rd Generation'),
       ('4th Generation'),
       ('5th Generation'),
       ('6th Generation'),
       ('7th Generation'),
       ('8th Generation'),
       ('9th Generation'),
       ('10th Generation'),
       ('11th Generation'),
       ('12th Generation'),
       ('13th Generation'),
       ('14th Generation');

